# Generated by Django 6.0.6 on 2026-06-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationtoken',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Kayıt aktivasyonu'), ('invite', 'Organizasyon daveti')], default='registration', max_length=20),
        ),
    ]
