# Generated by Django 6.0.6 on 2026-06-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_activationtoken_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Yönetici'), ('site_manager', 'Şantiye Şefi'), ('accountant', 'Muhasebe'), ('admin', 'Yönetici'), ('member', 'Üye')], default='member', max_length=20),
        ),
    ]
