# Generated by Django 6.0.6 on 2026-06-21 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_alter_customuser_role'),
        ('puantaj', '0004_remove_subcontractor_contract_unit_and_more'),
        ('sites', '0003_alter_site_budget_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('account_type', models.CharField(choices=[('payable', 'Borç (Taşeron)'), ('receivable', 'Alacak'), ('expense', 'Gider'), ('bank', 'Banka')], max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to='authentication.company')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tax_number', models.CharField(blank=True, max_length=32)),
                ('contact_phone', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='authentication.company')),
                ('subcontractor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor', to='puantaj.subcontractor')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('debit', 'Borç'), ('credit', 'Alacak')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('entry_date', models.DateField()),
                ('description', models.CharField(max_length=512)),
                ('source_type', models.CharField(choices=[('manual', 'Manuel'), ('hakedis_period', 'Hakediş Dönemi'), ('payment', 'Ödeme')], default='manual', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finans.ledgeraccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('hakedis_period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entry', to='puantaj.hakedisperiod')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='sites.site')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='finans.vendor')),
            ],
            options={
                'verbose_name_plural': 'ledger entries',
                'ordering': ['-entry_date', '-id'],
            },
        ),
    ]
