# Generated by Django 6.0.6 on 2026-06-21 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finans', '0001_initial'),
        ('sites', '0003_alter_site_budget_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(default='adet', max_length=32)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='sites.site')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('site', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Giriş'), ('out', 'Çıkış')], max_length=8)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('movement_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='finans.materialstockitem')),
            ],
            options={
                'ordering': ['-movement_date', '-id'],
            },
        ),
    ]
