# Generated by Django 6.0.6 on 2026-06-21 13:55

import daily_log.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0003_alter_site_budget_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(blank=True, max_length=64)),
                ('serial_number', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('available', 'Müsait'), ('assigned', 'Zimmetli'), ('maintenance', 'Bakımda'), ('retired', 'Emekli')], default='available', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='sites.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('weather', models.CharField(blank=True, max_length=64)),
                ('summary', models.TextField()),
                ('worker_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='sites.site')),
            ],
            options={
                'ordering': ['-log_date', '-id'],
                'unique_together': {('site', 'log_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyLogPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=daily_log.models.daily_log_photo_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='daily_log.dailylog')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
