# Generated by Django 6.0.6 on 2026-06-19 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_length_m', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('waste_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CuttingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter_mm', models.PositiveIntegerField()),
                ('stock_bar_index', models.PositiveIntegerField()),
                ('cuts', models.JSONField(default=list)),
                ('waste_m', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_plans', to='rebar_optimizer.optimizationrun')),
            ],
            options={
                'ordering': ['diameter_mm', 'stock_bar_index'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='projects/sources/')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('processing', 'İşleniyor'), ('ready', 'Hazır'), ('error', 'Hata')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='authentication.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='optimizationrun',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_runs', to='rebar_optimizer.project'),
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='rebar_optimizer.project')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RebarElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('column', 'Kolon'), ('beam', 'Kiriş'), ('slab', 'Döşeme'), ('other', 'Diğer')], max_length=20)),
                ('element_number', models.CharField(max_length=64)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='rebar_optimizer.floor')),
            ],
            options={
                'unique_together': {('floor', 'element_number')},
            },
        ),
        migrations.CreateModel(
            name='RebarRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter_mm', models.PositiveIntegerField(help_text='Demir çapı (mm), örn: 16')),
                ('length_m', models.DecimalField(decimal_places=2, help_text='Boy (metre)', max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('element_ref', models.CharField(blank=True, help_text='K-101, D-203 vb.', max_length=64)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='rebar_optimizer.rebarelement')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='rebar_optimizer.floor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='rebar_optimizer.project')),
            ],
            options={
                'ordering': ['diameter_mm', '-length_m'],
            },
        ),
    ]
