# Generated by Django 6.0.6 on 2026-06-20 14:53

import django.db.models.deletion
import metraj.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_role'),
        ('metraj', '0002_seed_categories'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metrajcategory',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Boş = tüm şirketler için varsayılan kategori', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metraj_categories', to='authentication.company'),
        ),
        migrations.AddField(
            model_name='metrajcategory',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Kullanıcı tarafından eklenen kategori'),
        ),
        migrations.AlterField(
            model_name='metrajcategory',
            name='slug',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='metrajcategory',
            unique_together={('company', 'slug')},
        ),
        migrations.CreateModel(
            name='MetrajDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=metraj.models.metraj_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('file_kind', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('word', 'Word'), ('image', 'Görsel'), ('other', 'Diğer')], default='other', max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metraj_documents', to='sites.site')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metraj_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
