# Generated by Django 6.0.6 on 2026-06-21 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metraj', '0008_metrajoperation_time_unique'),
        ('puantaj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrajitem',
            name='subcontractor',
            field=models.ForeignKey(blank=True, help_text='Bu kalemi yürüten taşeron', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metraj_items', to='puantaj.subcontractor'),
        ),
        migrations.AlterField(
            model_name='metrajitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taşeron sözleşme birim fiyatı (bu kalem için)', max_digits=14, null=True),
        ),
    ]
