# Generated by Django 6.0.6 on 2026-06-21 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_role'),
        ('metraj', '0009_metrajitem_subcontractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PozTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('default_unit', models.CharField(default='m2', max_length=20)),
                ('default_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poz_templates', to='metraj.metrajcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poz_templates', to='authentication.company')),
            ],
            options={
                'ordering': ['category__sort_order', 'description', 'id'],
            },
        ),
        migrations.AddField(
            model_name='metrajitem',
            name='poz_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metraj_items', to='metraj.poztemplate'),
        ),
    ]
