# Generated by Django 6.0.6 on 2026-06-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_site_extended_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='budget_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Planlanan toplam bütçe', max_digits=14, null=True),
        ),
    ]
