# Generated by Django 6.0.6 on 2026-06-21 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metraj', '0008_metrajoperation_time_unique'),
        ('sites', '0003_alter_site_budget_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trade', models.CharField(choices=[('rebar', 'Demirci'), ('plaster', 'Sıvacı'), ('formwork', 'Kalıpçı'), ('paint', 'Boyacı'), ('electric', 'Elektrik'), ('plumbing', 'Tesisat'), ('general', 'Genel')], default='general', max_length=20)),
                ('contract_unit', models.CharField(choices=[('worker_day', 'İşçi-gün'), ('m2', 'm²'), ('m3', 'm³'), ('lump', 'Götürü')], default='worker_day', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractors', to='sites.site')),
            ],
            options={
                'ordering': ['name', 'id'],
                'unique_together': {('site', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('worker_count', models.PositiveSmallIntegerField(default=1)),
                ('work_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='m²/m³ sözleşmeleri için günlük miktar', max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets_created', to=settings.AUTH_USER_MODEL)),
                ('metraj_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='metraj.metrajitem')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='sites.site')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='puantaj.subcontractor')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('subcontractor', 'date'), name='timesheet_unique_subcontractor_day')],
            },
        ),
    ]
