# Generated by Django 6.0.6 on 2026-06-21 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metraj', '0009_metrajitem_subcontractor'),
        ('puantaj', '0002_subcontractor_category'),
        ('sites', '0003_alter_site_budget_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('approved', 'Onaylandı'), ('disputed', 'İtirazlı')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField()),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='sites.site')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='puantaj.subcontractor')),
            ],
            options={
                'ordering': ['payment_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HakedisPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('pending_approval', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('paid', 'Ödendi')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_retainage', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_advance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hakedis_periods_approved', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hakedis_periods_prepared', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hakedis_periods', to='sites.site')),
            ],
            options={
                'ordering': ['-period_end', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HakedisPeriodLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('prev_cumulative_percent', models.PositiveSmallIntegerField(default=0)),
                ('current_cumulative_percent', models.PositiveSmallIntegerField(default=0)),
                ('delta_percent', models.PositiveSmallIntegerField(default=0)),
                ('line_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('metraj_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hakedis_period_lines', to='metraj.metrajitem')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='puantaj.hakedisperiod')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hakedis_period_lines', to='puantaj.subcontractor')),
            ],
            options={
                'ordering': ['subcontractor__name', 'metraj_item__id'],
            },
        ),
        migrations.CreateModel(
            name='HakedisPeriodSubcontractorDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retainage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_deductions', to='puantaj.hakedisperiod')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hakedis_deductions', to='puantaj.subcontractor')),
            ],
        ),
        migrations.CreateModel(
            name='SubcontractorContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(blank=True, max_length=64)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('scope', models.TextField(blank=True, help_text='Sözleşme kapsamı')),
                ('retainage_percent', models.DecimalField(decimal_places=2, default=0, help_text='Teminat kesintisi yüzdesi', max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('active', 'Aktif'), ('closed', 'Kapalı')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='puantaj.subcontractor')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='hakedisperiod',
            constraint=models.UniqueConstraint(fields=('site', 'period_start', 'period_end'), name='hakedis_period_unique_site_range'),
        ),
        migrations.AddConstraint(
            model_name='hakedisperiodline',
            constraint=models.UniqueConstraint(fields=('period', 'metraj_item'), name='hakedis_period_line_unique_item'),
        ),
        migrations.AddConstraint(
            model_name='hakedisperiodsubcontractordeduction',
            constraint=models.UniqueConstraint(fields=('period', 'subcontractor'), name='hakedis_deduction_unique_sub'),
        ),
    ]
