# Generated by Django 6.0.6 on 2026-06-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puantaj', '0003_faz_a_hakedis_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcontractor',
            name='contract_unit',
        ),
        migrations.RemoveField(
            model_name='subcontractor',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='metraj_item',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='work_quantity',
        ),
    ]
